### ISSUE TITLE
NG8 and angular universal = Duplicated pageviews

### ISSUE THREAD

**Issue by marcosybarraa** [maxandriani/ngx-google-analytics#11]
Use case:
Using ng8 with angular univesal SSR, pages views are duplicated.
Tried with configuration NgxGoogleAnalyticsRouterModule
Tried without NgxGoogleAnalyticsRouterModule and using in component constructor  .pageview()

Result is pages views are duplicated

**Comment by maxandriani** [comment]
Hi! I'm releasing an update write now and I have done some changes on NgxGoogleAnalyticsRoutingModule. But to be honest, I don't know if your use case will be affected.

Basically, my RouterModule just subscribe on Angular's Router events and looks for a NavigationEnd. Every time Router trigger this event I call a `gtag()` w/ a page view.

I fixed the cleanup issues when bootstrap component is destroyed, but it will duplicate page view only if you have multiple bootstrap components and some how you dimanicaly rebuild this on the fly.

There is other known behaviour, the first `gtag` command is a config w/ tracking ID. And then when your Router calls NavigationEnd there is another pageView trigger. But I think Google Analytics should ignore the first page view and assume de second as the official page view. That "duplicated" page view only occurs on application setup. All other page view call is triggered by Router.

A simply workarround could be skip the first NavigationEnd on Router subcription pipeline.

```ts
const subs = router
      .events
      .pipe(skip(1), takeUntil(this.onDestroy$))
      .subscribe(event => {
        if (event instanceof NavigationEnd) {
          gaService.pageView(event.urlAfterRedirects, undefined);
        }
      });
```
