### ISSUE TITLE
How to disable the plugin until I receive cookie consent?

### ISSUE THREAD

**Issue by CucumberKing** [maxandriani/ngx-google-analytics#111]
How can I disable the plugin until I receive cookie consent? I live in the EU and need to be careful when using GA. Is it possible to allow any connection to Google only after the user has given their consent? Thank you.

**Comment by bable3** [comment]
did you find the solution ?

**Comment by ekorian** [comment]
It seems to work with `window["ga-disable-"+trackingId] = true`, and then to `false` when consent is received.
