### ISSUE TITLE
Was not possible create or read gtag() 

### ISSUE THREAD

**Issue by krychuq1** [maxandriani/ngx-google-analytics#19]
Hi, 

I'm getting error: 

Was not possible create or read gtag() fn. Make sure this module is running on a Browser w/ access to Window interface.

Error appears only on server side rending.

angular version: 10.1.2
angular universal 10.0.1

**Comment by maxandriani** [comment]
This error is thrown because the version of Google Analytics api that we use has dependency on Browser's Window Interface. So, it does not work on server side apps.
