### ISSUE TITLE
A way for user opt-out? 

### ISSUE THREAD

**Issue by fingust** [maxandriani/ngx-google-analytics#21]
GDPR states that any cookies except those that are strictly necessary for website to function properly have to be accepted by user before you can create them. Is it possible to dynamically change whether or not it tracks user with this module? I've seen there's a 'enableTracing' parameter in .forRoot() method but even if I pass in false it still tracks the user, and that value cannot be changed dynamically.

**Comment by fingust** [comment]
Found a workaround with google's original way of disabling analytics.

Following line can be added in main.ts file and you can implement your logic for enabling / disabling there, but it still can't be changed dynamically without reloading the page. 

`
window['ga-disable-UA-XXXXX-Y'] = true;`

**Comment by maxandriani** [comment]
Hello @fingust !

Actually my module loads Google Analytics on Angular's startup time, and it is not possible to change anything after this life cicle w/o restart the whole application.

I don't have much time to provide this feature now, but feel free to make a PR. You have to change code on gaInitilizer, GaService and GaSettings.

But you can create a new factory and attach to APP_BOOTSTRAP life cycle to manage you logic and add the `window['ga-disable-UA-XXXXX-Y'] = true;` command dinamically. There are more considerations when use multiple tracking codes that you should call de initial commands again for every tracking code change.
