### ISSUE TITLE
Support gtag's set command

### ISSUE THREAD

**Issue by mrahhal** [maxandriani/ngx-google-analytics#22]
It doesn't look like the [set command](https://developers.google.com/analytics/devguides/collection/gtagjs/setting-values) is supported in [GoogleAnalyticsService](https://github.com/maxandriani/ngx-google-analytics/blob/master/projects/ngx-google-analytics/src/lib/services/google-analytics.service.ts).

**Comment by maxandriani** [comment]
@mrahhal It is true, GoogleAnalyticsService does't have set method yet. Did you tried `gtag()` alias? If `gtag()` works it'll be easy to enhance kk

**Comment by mrahhal** [comment]
Ah, but [this page](https://developers.google.com/analytics/devguides/collection/gtagjs/setting-values) shows the following snippet:
```
gtag('set', {
  'currency': 'USD',
  'country': 'US'
});
```

So I thought it exists.

> Did you tried gtag() alias?
This method takes 3 arguments (with the first 2 being the command and the action), so no this doesn't work, as I've also looked at its impl.

Implementing set itself in the service should be super easy:
```
set(action: string, ...options: Array<any>) {
    try {
      this._gtag('set', ...options);
    } catch (err) {
      this.throw(err);
    }
  }
```
