### ISSUE TITLE
Uncaught TypeError: Object(...) is not a function

### ISSUE THREAD

**Issue by tsadkan** [maxandriani/ngx-google-analytics#24]
Bug 🐛 🐛 (May be 🤔)

I have installed the package and import the package as stated in the documentation but it throws   TypeError: Object(...) is not a function.

Which version of angular, and which browser/ OS affected by this issuse? Did this work in previuos versions of Angular?

Here are my installed packages version 

"dependencies" : {
  "ngx-google-analytics": "^9.0.1",
  "typescript": "~3.2.2",
  "tslib": "^1.9.0",
  "@angular/cli": "~7.3.3",
  "@angular/router": "^7.2.0"
}

Screenshot

![Screenshot from 2020-09-15 10-04-43](https://user-images.githubusercontent.com/20349976/93177110-f5aad980-f73a-11ea-8a2f-5e64ca281069.png)

**Comment by maxandriani** [comment]
It seems like your angular version is under the required. ngx-google-analytics@0.0.8 is the last version that covers angular 7+.

After that i have link the package major w/ angular major.
