### ISSUE TITLE
gtag not working at all

### ISSUE THREAD

**Issue by nimeshk-itpath** [maxandriani/ngx-google-analytics#26]
I'm using latest version of this package and events are just working fine but I'm trying to setup userid dynamically by using below code but no error and no output is showing on google:

constructor(private _formBuilder: FormBuilder, private _spinner: SpinnerComponent,
    private _eventService: EventService, private router: Router,
    private $gaService: GoogleAnalyticsService
  ) { 
    
  }

submitForm(): void {
    
// this should  be work

    this.$gaService.gtag('set', {'user_id': 'sessuid-2'});
}

**Comment by maxandriani** [comment]
That is interesting because all directives and componentes rely on NgxGoogleAnalyticsService.gtag() function. Not all gtag call produces an http request. Did you checked in the `window.dataLayer` object if your call was there? I also use a Chrome plugin GA Debug to help me test gtag commands.

**Comment by nimeshk-itpath** [comment]
Late reply 💯 project finished ! :)
