### ISSUE TITLE
[Feature] Allow to send custom events

### ISSUE THREAD

**Issue by Jiiieeef** [maxandriani/ngx-google-analytics#32]
Hello,

I am currently working on a new product for my job and my PO need custom events in GA such as:

```
this.$gaService.event('create_entity', {
    entityName: 'my entity',
    startDate: new Date()
});
```

Do you think it's possible ? I read the documentation and the code and I don't find anything :(

Thanks.

**Comment by maxandriani** [comment]
Hi @Jiiieeef. In short No! You should read the Google Analytics API to better understand how events works.

https://support.google.com/analytics/answer/1033068#Anatomy
https://developers.google.com/analytics/devguides/collection/analyticsjs/events#implementation

This wrapper provides support to the majorit of use case scenarios on `event()` method, but not all. For a out of edge use case, you can use the `gtag()` method directlly. It provides direct access to gtag function.

**Comment by arobert93** [comment]
Hi @maxandriani , according to official docs you can set custom dimensions and metrics (https://developers.google.com/analytics/devguides/collection/gtagjs/custom-dims-mets). I believe your library should support it by default. I've been working for 5 years and data architect and is the most required feature in such implementations.

This is just my personal opinion.
