### ISSUE TITLE
Disable tracking for dev environment

### ISSUE THREAD

**Issue by nikolayr1** [maxandriani/ngx-google-analytics#37]
How can i disable ga events tracking while developing on localhost? or on my staging environment?

**Comment by maxandriani** [comment]
@nikolayr1 Just provide an empty tracking code on dev stage.

`NgxGoogleAnalyticsModule.forRoot(environment.production ? ‘Real-code’ : ‘’);`

**Comment by aman-koco** [comment]
If I use the above method, I am getting the below error on page load - 
` Empty tracking code for Google Analytics. Make sure to provide one when initializing NgxGoogleAnalyticsModule.`

In the environment files for which I do not want to have GA, I have entered as blank i.e `GA: ''`
Any idea how to resolve the error?

**Comment by maxandriani** [comment]
@aman-koco I think it is not possible. This lib was designed to consume trackingCode by angular's DI system. You can do not call `NgxGoogleAnalyticsModule.forRoot`, but you shall handle mannualy the providers to `NGX_GOOGLE_ANALYTICS_SETTINGS_TOKEN`.

The tracking code is used on `initialization` phase and by argument on pageViews as well.

You can mannualy handle the GA initialization by calling
`
export function GoogleAnalyticsInitializer(
  settings: IGoogleAnalyticsSettings,
  gtag: GtagFn,
  document: Document
)();
`

You can read more about it on https://github.com/maxandriani/ngx-google-analytics/issues/40
