### ISSUE TITLE
`ɵɵdefineInjectable` and `ɵɵinject` warnings

### ISSUE THREAD

**Issue by jwright04** [maxandriani/ngx-google-analytics#4]
# 🐞 bug report

### Affected Package
@angular/core

### Is this a regression?
Not sure, could be an issue with current version of Angular 6

### Description

After installation, I'm seeing the following warnings: `ɵɵdefineInjectable` and `ɵɵinject` after starting my application
 

## 🔬 Minimal Reproduction
Installing with Angular 6.1.10

## 🔥 Exception or Error
<pre><code>

WARNING in ./node_modules/ngx-google-analytics/fesm5/ngx-google-analytics.js 440:64-82
"export 'ɵɵdefineInjectable' was not found in '@angular/core'

WARNING in ./node_modules/ngx-google-analytics/fesm5/ngx-google-analytics.js 440:172-180
"export 'ɵɵinject' was not found in '@angular/core'

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 6.0.8
Node: 10.16.0
OS: darwin x64
Angular: 6.1.10
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.9
@angular-devkit/build-angular     0.13.9
@angular-devkit/build-optimizer   0.13.9
@angular-devkit/build-webpack     0.13.9
@angular-devkit/core              7.3.9
@angular-devkit/schematics        0.6.8
@angular/cli                      6.0.8
@ngtools/webpack                  7.3.9
@schematics/angular               0.6.8
@schematics/update                0.6.8
rxjs                              6.5.2
typescript                        2.8.4
webpack                           4.29.0

</code></pre>

**Comment by maxandriani** [comment]
It seens a problem w/ angular major version.

I'll build one version of this package to each angular major, but I don't have much time this week.
