### ISSUE TITLE
forRoot commands not working

### ISSUE THREAD

**Issue by robinpellegrims** [maxandriani/ngx-google-analytics#46]
The commands passed as the second argument in `NgxGoogleAnalyticsModule.forRoot` don't seem to be executed. 

At first sight, it seems to be related to a different naming of the `commands`/`initCommands` properties.

In [`NgxGoogleAnalyticsModule`](https://github.com/maxandriani/ngx-google-analytics/blob/e3b3b177904595ea3900cd323c559daeed601d56/projects/ngx-google-analytics/src/lib/ngx-google-analytics.module.ts#L49):
```typescript
{
    provide: NGX_GOOGLE_ANALYTICS_SETTINGS_TOKEN,
    useValue: {
        trackingCode,
        commands,
        uri,
        enableTracing,
        nonce
    }
},
```

In [`GoogleAnalyticsInitializer`](https://github.com/maxandriani/ngx-google-analytics/blob/e3b3b177904595ea3900cd323c559daeed601d56/projects/ngx-google-analytics/src/lib/initializers/google-analytics.initializer.ts#L64):
```typescript
settings.initCommands = [ ...initialCommands, ...(settings.initCommands || []) ];
```

In [`IGoogleAnalyticsSettings`](https://github.com/maxandriani/ngx-google-analytics/blob/e3b3b177904595ea3900cd323c559daeed601d56/projects/ngx-google-analytics/src/lib/interfaces/i-google-analytics-settings.ts#L10) the property is also named `initialCommands` so I'm guessing it should be `initialCommands` in the provided value in NgxGoogleAnalyticsModule.

**Comment by maxandriani** [comment]
I'll take a wile to publish this fix, so meanwhile you can workaround this issue by override the Settings Token Provider w/ the valid property name.

**Comment by nostop8** [comment]
#49 this should fix the issue?

**Comment by maxandriani** [comment]
This fix will be published in the next release
