### ISSUE TITLE
Add AppVerison?

### ISSUE THREAD

**Issue by webben-de** [maxandriani/ngx-google-analytics#54]
Hey,
is it possbile to add a application version somewhere on initialization when i import the root module? f.e. as a parameter object there
like:

![ngx-analytics-prop](https://user-images.githubusercontent.com/7140421/114173910-29985700-9938-11eb-8224-f4c2825dc9b0.png)

**Comment by maxandriani** [comment]
@webben-de 

```
NgxGoogleAnalyticsModule.forRoot(
  'tracking-code',
  [
    { command: 'set', values: [ 'appName', 'name' ] },
    { command: 'set', values: [ 'appVersion', version ] }
  ]);
```
