### ISSUE TITLE
Enable/Set send_page_view, client_storage and other config values.

### ISSUE THREAD

**Issue by SamanthaAdrichem** [maxandriani/ngx-google-analytics#55]
Our team asks me to setup this config on init of the analytics module

_gtag('config', analyticsConfig.id, { send_page_view : true, client_storage : 'none', anonymize_ip : true, });

Now I see that the NgxGoogleAnalyticsModule.forRoot has a second argument, but that expects the values to be an array.

Would this be solved by just calling:

```
this.googleAnalyticsService.gtag(
	'config',
	{
		send_page_view: true,
		client_storage: 'none',
		anonymize_ip: true
	},
);
```

Or are you supposed to do this? (the `<any>` causes us to be able to send in a string value instead of an array value)

```
NgxGoogleAnalyticsModule.forRoot(AppConfig.googleAnalytics.id, <any>{send_page_view: true, client_storage: 'none', anonymize_ip: true}),
```

**Comment by maxandriani** [comment]
@SamanthaAdrichem 

```
NgxGoogleAnalyticsModule.forRoot(
  'tracking-code',
  [
    {
       command: 'config',
       values: [
         analyticsConfig.id,
         {
           send_page_view, true,
           client_storage, 'none',
	   anonymize_ip, true
         }
       ]
    }
  ]
);
```

**Comment by SamanthaAdrichem** [comment]
@maxandriani thank you for your reply!
