### ISSUE TITLE
Add tracking code on the fly

### ISSUE THREAD

**Issue by returnvoid** [maxandriani/ngx-google-analytics#6]
Hi, looking for a library like this but I was wondering if this will support adding another tracking-code dynamically. 

thanks

**Comment by maxandriani** [comment]
Hi @returnvoid! Can you please talk a little bit more about why you need this behavior? I would like to understand more the problem that you are trying to solve.

Actually, I think you are already able to change  the “current” tracking id on the fly.

In the Google Docs, we can see that the follow lines starts the tracking.

`
gtag('js', new Date());
gtag('config', 'UA-86212554-1'); 
`

So, I think you can reset the current tracking just call the above commands on our “ GoogleAnalyticsService.gtag()” method.

`
...
constructor(private ga: GoogleAnalyticsService) {}

...
onChange() {
  this.ga.gtag(“js”, new Date());
  this.ga.gtag(“config”, “new code”);
}
`

Be aware that after change the tracking code config, you can’t trigger events on the previous tracking code anymore.

If you want a more efficient approach, you should provide an factory function to the NGX_GOOGLE_ANALYTICS_SETTINGS_TOKEN on AppModule.

**Comment by returnvoid** [comment]
> Hi @returnvoid! Can you please talk a little bit more about why you need this behavior? I would like to understand more the problem that you are trying to solve.
> 
> Actually, I think you are already able to change the “current” tracking id on the fly.
> 
> In the Google Docs, we can see that the follow lines starts the tracking.
> 
> `gtag('js', new Date()); gtag('config', 'UA-86212554-1'); `
> 
> So, I think you can reset the current tracking just call the above commands on our “ GoogleAnalyticsService.gtag()” method.
> 
> `
> ...
> constructor(private ga: GoogleAnalyticsService) {}
> 
> ...
> onChange() {
> this.ga.gtag(“js”, new Date());
> this.ga.gtag(“config”, “new code”);
> }
> `
> 
> Be aware that after change the tracking code config, you can’t trigger events on the previous tracking code anymore.
> 
> If you want a more efficient approach, you should provide an factory function to the NGX_GOOGLE_ANALYTICS_SETTINGS_TOKEN on AppModule.

**Comment by returnvoid** [comment]
Thanks for responding @maxandriani 
Well what I need to do is to add a second tracking code after calling an endpoint where I will get the second trackingId. It's basically this:

<script async src="https://www.googletagmanager.com/gtag/js?id=GA_TRACKING_ID"></script> //<----- first trackingId

  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', 'GA_TRACKING_ID'); // <---- second trackingId is what I need
  </script>

I saw that method gtag() and I tried different ways (just guessing) but they didn't work:

this.$gaService.gtag('config', 'TRACKING_ID', 'auto');

thanks

**Comment by Rupesh-Vitekar** [comment]
@maxandriani
how to use 
`@Inject(NGX_GOOGLE_ANALYTICS_SETTINGS_TOKEN) gaConfig: IGoogleAnalyticsSettings` 
in App.component.ts
can you share any example please

**Comment by maxandriani** [comment]
@Rupesh-Vitekar Hi! look at this thread #40. Currently there is no easy way yet to start ga on the fly. I'm working on it but I have very little free time to work with.
