### ISSUE TITLE
TS1086: An accessor cannot be declared in an ambient context

### ISSUE THREAD

**Issue by alavaros** [maxandriani/ngx-google-analytics#64]
I just installed the library and when I start the application I get the following error:
```
ERROR in node_modules/ngx-google-analytics/lib/directives/ga-event-form-input.directive.d.ts(5,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/ngx-google-analytics/lib/directives/ga-event.directive.d.ts(20,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/ngx-google-analytics/lib/directives/ga-event.directive.d.ts(21,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/ngx-google-analytics/lib/services/google-analytics.service.d.ts(8,17): error TS1086: An accessor cannot be declared in an ambient context.
```

Versions:
- Angular: 8.2.14
- ngx-google-analytics: 11.2.1

**Comment by maxandriani** [comment]
Hello @alavaros. I have sync the major version of this lib w/ angular’s major to prevent compatibility issues. So you should use ngx-google-analytics@8.x w/ @angular@8

**Comment by alavaros** [comment]
> Hello @alavaros. I have sync the major version of this lib w/ angular’s major to prevent compatibility issues. So you should use [ngx-google-analytics@8.x](mailto:ngx-google-analytics@8.x) w/ @angular@8

Thanks @maxandriani, I didn't realize about version compatibility, thank you very much.
