### ISSUE TITLE
Multiple Tracking codes

### ISSUE THREAD

**Issue by laeciofernando** [maxandriani/ngx-google-analytics#7]
Is there a way to use multiple tracking codes?
Something like:
NgxGoogleAnalyticsModule.forRoot('tracking-code1', 'tracking-code2');

**Comment by maxandriani** [comment]
Yes and No.

There is not a designed way to do that. But the all settings relly on Angular DI, aka, InjectionToken. So you can easily create copies os GoogleAnalyticsService and NGX_GOOGLE_ANALYTICS_SETTINGS_TOKEN to each "environment".

If you stil want this behaviour, please post here the Google Documentation of this behaviour and I'll Study a design for that.

**Comment by tskweres** [comment]
@maxandriani Looking for something similar to this. I have a B2B app where my clients need to be able to add their GTA tracking code, but it only tracks on their specific pages, they can't view other clients' stats. 

So i need to be able to dynamically change the GTA tracking code based on the route or support multiple codes. Any thoughts?

**Comment by mohammedmatar** [comment]
hi @maxandriani, according to your last comment, here is the documentation,

https://developers.google.com/analytics/devguides/collection/analyticsjs/creating-trackers#working_with_multiple_trackers

**Comment by mohammedmatar** [comment]
i can do multiple tracking without this library like this:

inside my index.html
```html
<script>
            (function(i, s, o, g, r, a, m) {
                i['GoogleAnalyticsObject'] = r;
                (i[r] =
                        i[r] ||
                        function() {
                            (i[r].q = i[r].q || []).push(arguments);
                        }),
                        (i[r].l = 1 * new Date());
                (a = s.createElement(o)), (m = s.getElementsByTagName(o)[0]);
                a.async = 1;
                a.src = g;
                m.parentNode.insertBefore(a, m);
            })(window, document, 'script', 'https://www.google-analytics.com/analytics.js', 'ga');
        </script>
```
---
 and inside my app.component.ts

```typescript
         if ((<any>window).ga != null) {
                (<any>window).ga('create', this.gaId[0], 'auto');
                for (let i = 0; i < this.gaId.length; i++) {
                    const trackingId = this.gaId[i];
                    (<any>window).ga('create', trackingId, 'auto', `t${i}`); // add your tracking ID here.
                }

                this.router.events.subscribe(event => {
                    try {
                        if (typeof ga === 'function') {
                            if (event instanceof NavigationEnd) {
                                ga('set', 'page', event.urlAfterRedirects);
                                ga('send', 'pageview');
                                for (let i = 0; i < this.gaId.length; i++) {
                                    ga(`t${i}.set`, 'page', event.urlAfterRedirects);
                                    ga(`t${i}.send`, 'pageview');
                                }
                            }
                        }
                    } catch (e) {
                        console.log(e);
                    }
                });
            }
            ```
but I already using your library, so I think will be better, if we could add this ability to the library.

thanks.

**Comment by maxandriani** [comment]
I know that implement multiple tracking code is easy on GA side. But on the lib it is not so easy.

I have to refactor all GaService class and GaEvent directives to handle contexts (tracking codes).

Ok, it is easy to change de trackingCode into an array w/ multiple tracking codes, and then register all of then...

But, GaService must know with tracking code to use when send the commands, or at least enable the ability of handle contexts w/o breaking the existing api... Something like
```js

onSubmitEvent() {
   this.gaService
      .withContext('tracking-name')
      .event(...);
}
```

Then, maybe we can create another directive like `GaContext` to handle which tracking code to use when click on UI elements....

```
<div class="page-wrapper" gaContext="tracking-name">
   ...
   <form gaCategory="user-form">
       <input gaEvent="user-name" />
       ...
   </form>
</div>
```

So.. it is not an easy hotfix.

**Comment by rolivares** [comment]
> NGX_GOOGLE_ANALYTICS_SETTINGS_TOKEN

I think this is a good option for me ... I would like an example in order to achieve that 

anyone ?

**Comment by quangman96** [comment]
> ```js
> withTracker
> ```

I did not find the withTracker attribute in the gaService. What version does it start from?
