### ISSUE TITLE
Question: does using this plugin still require the GA code snippet?

### ISSUE THREAD

**Issue by smlombardi** [maxandriani/ngx-google-analytics#71]
It's not in the instructions, but I am assuming using this library still requires adding the JS snippet provided by Google in index.html?

```
<!-- Google Analytics -->
<script>
(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
})(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

ga('create', 'UA-XXXXX-Y', 'auto');
ga('send', 'pageview');
</script>
<!-- End Google Analytics -->
```

I have been using it with the line `ga('send', 'pageview');` commented out.

Is this correct, or can this whole code block be omitted?

**Comment by maxandriani** [comment]
@smlombardi his lib creates the snippet for you at `NgxGoogleAnalyticsModule.forRoot()`.
