### ISSUE TITLE
add ability to init outside the app.module.ts

### ISSUE THREAD

**Issue by rbalet** [maxandriani/ngx-google-analytics#74]
This is a specific use case and maybe you guys have a better way of dealing with it but. 

### Problem
I receive the api token through the api, so I'm not able to use the `.forRoot` method, since I don't know the token

### Solution
Being able init the service through the following method.

```typescript
  initGoogleAnalytics(
    settings: IGoogleAnalyticsSettings,
    gtag: GtagFn = this._gtag,
    document = this.document,
  ) {
  // ...
}
```

Or does somebody have an Idea how I could resolve this issue ?

**Comment by maxandriani** [comment]
@rbalet I is ok o call `GoogleAnalyticsInitializer(settings, gtagRef, documentRef)` mannually.

See https://github.com/maxandriani/ngx-google-analytics/blob/master/projects/ngx-google-analytics/src/lib/initializers/google-analytics.initializer.ts and #40
