### ISSUE TITLE
Google Consent Mode

### ISSUE THREAD

**Issue by Helveg** [maxandriani/ngx-google-analytics#89]
Google added a beta for _Consent Mode_, where the user consent level can be set and cookieless tracking accordign to the user's privacy settings can be done. Is this supported yet in `ngx-google-analytics`?

**Comment by erzzo** [comment]
@maxandriani and this should block the requests that are sent to GA? Because I have implemented it like described, but I still see that the requests are sent to GA

**Comment by olepogam** [comment]
Please mind second parameter in NgxGoogleAnalyticsModule.forRoot() is an array : should be [ { ... } ]
