### ISSUE TITLE
Can't import the named export 'ɵɵngDeclareNgModule' from non EcmaScript module (only default export is available)

### ISSUE THREAD

**Issue by ilirbeq** [maxandriani/ngx-google-analytics#92]
I am having a lot of errors like that one in the title above when trying to serve or build the app. 

- Installed the library, 
- Generated the measurementId from Google Analytics page
- Imported **NgxGoogleAnalyticsModule.forRoot('X-XXXXXXXX')** in **AppModule**

Below you can see the Angular Version I use in my project. 

"@angular/animations": "^11.2.14",
    "@angular/common": "^11.2.14",
    "@angular/compiler": "^11.2.14",
    "@angular/core": "^11.2.14",
    "@angular/forms": "^11.2.14",
    "@angular/localize": "^11.2.14",
    "@angular/platform-browser": "^11.2.14",
    "@angular/platform-browser-dynamic": "^11.2.14",
    "@angular/router": "^11.2.14",
    "@ckeditor/ckeditor5-angular": "^1.2.3",
    "@fortawesome/fontawesome-free": "^5.14.0",
    "@ng-bootstrap/ng-bootstrap": "^9.1.3",
    "@ng-select/ng-select": "^6.1.0",
    "@types/jquery": "^3.3.33",
    "angular-oauth2-oidc": "^10.0.3",
    "bootstrap": "^4.6.0",
    "compass-mixins": "^0.12.10",
    "exceljs": "^1.12.0",
    "file-saver": "^2.0.2",
    "guid-typescript": "^1.0.9",
    "highcharts": "^8.0.4",
    "jquery": "^3.5.1",
    "jwt-decode": "^3.1.2",
    "lightgallery": "^2.4.0",
    "ng5-slider": "^1.2.4",
    "ngx-bootstrap": "^5.3.2",
    "ngx-google-analytics": "^13.0.1",
    
    FYI, Nx dev tools are also being used.

**Comment by maxandriani** [comment]
@ilirbeq it seems you are using ng@11 version. You should use ngx-google-analytics@11 as well or upgrade your environment to ng@13.

**Comment by ilirbeq** [comment]
@maxandriani Yeah that was the issue. Since the library supported Angular 8+ versions I thought I can use the latest version of it. 

But anyway, thanks for your response.
